minimum_movement_delay = 0.05
unstuck_movement_delay = 2.4
unstuck_movement_hold_time = 1.4
perceived_tile_size = 35
player_collision_radius = 24
wall_model_classes = [ "wall", "bush", "close_bush",]
gadget_pixels_minimum = 1300.0
hypercharge_pixels_minimum = 1800.0
super_pixels_minimum = 1800.0
idle_pixels_minimum = 75000.0
decline_team_invites = true
buffie_hold_seconds = 5.0
team_invite_green_minimum = 3500
team_invite_mute_x = 0.89
team_invite_mute_y = 0.29
centered_wall_detection = false
poison_gas_fraction = 0.078
wall_detection_confidence = 0.5
entity_detection_confidence = 0.65
seconds_to_hold_attack_after_reaching_max = 1.5
play_again_on_win = "yes"
current_playstyle = "unified_dodge.pyla"
stop_at = ""
resume_at = ""
close_game_when_scheduled = true
shutdown_when_done = true
enemy_exposure_radius = 40
attack_range_multiplier = 1.35
