cpu_or_gpu = "auto"
max_ips = "auto"
trophies_multiplier = 1
run_for_minutes = 0
emulator_port = 5037
api_base_url = "default"
brawl_stars_package = "bsd.suitcase.release"
ocr_scale_down_factor = 0.8
used_threads = "auto"
player_tag = ""
default_trophy_target = 1000
auto_load_queue_on_startup = true
play_order = "in_order"
